<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('countries')->truncate();

        $countries = [
           ['name' => ['ar' => 'أفغانستان', 'en' => 'Afghanistan'], 'code' => 'AF'],
            ['name' => ['ar' => 'ألبانيا', 'en' => 'Albania'], 'code' => 'AL'],
            ['name' => ['ar' => 'الجزائر', 'en' => 'Algeria'], 'code' => 'DZ'],
            ['name' => ['ar' => 'أندورا', 'en' => 'Andorra'], 'code' => 'AD'],
            ['name' => ['ar' => 'أنغولا', 'en' => 'Angola'], 'code' => 'AO'],
            ['name' => ['ar' => 'أنتيغوا وبربودا', 'en' => 'Antigua and Barbuda'], 'code' => 'AG'],
            ['name' => ['ar' => 'الأرجنتين', 'en' => 'Argentina'], 'code' => 'AR'],
            ['name' => ['ar' => 'أرمينيا', 'en' => 'Armenia'], 'code' => 'AM'],
            ['name' => ['ar' => 'أستراليا', 'en' => 'Australia'], 'code' => 'AU'],
            ['name' => ['ar' => 'النمسا', 'en' => 'Austria'], 'code' => 'AT'],
            ['name' => ['ar' => 'أذربيجان', 'en' => 'Azerbaijan'], 'code' => 'AZ'],
            ['name' => ['ar' => 'البهاما', 'en' => 'Bahamas'], 'code' => 'BS'],
            ['name' => ['ar' => 'البحرين', 'en' => 'Bahrain'], 'code' => 'BH'],
            ['name' => ['ar' => 'بنغلاديش', 'en' => 'Bangladesh'], 'code' => 'BD'],
            ['name' => ['ar' => 'باربادوس', 'en' => 'Barbados'], 'code' => 'BB'],
            ['name' => ['ar' => 'بيلاروسيا', 'en' => 'Belarus'], 'code' => 'BY'],
            ['name' => ['ar' => 'بلجيكا', 'en' => 'Belgium'], 'code' => 'BE'],
            ['name' => ['ar' => 'بليز', 'en' => 'Belize'], 'code' => 'BZ'],
            ['name' => ['ar' => 'بنين', 'en' => 'Benin'], 'code' => 'BJ'],
            ['name' => ['ar' => 'بوتان', 'en' => 'Bhutan'], 'code' => 'BT'],
            ['name' => ['ar' => 'بوليفيا', 'en' => 'Bolivia'], 'code' => 'BO'],
            ['name' => ['ar' => 'البوسنة والهرسك', 'en' => 'Bosnia and Herzegovina'], 'code' => 'BA'],
            ['name' => ['ar' => 'بوتسوانا', 'en' => 'Botswana'], 'code' => 'BW'],
            ['name' => ['ar' => 'البرازيل', 'en' => 'Brazil'], 'code' => 'BR'],
            ['name' => ['ar' => 'بروناي', 'en' => 'Brunei'], 'code' => 'BN'],
            ['name' => ['ar' => 'بلغاريا', 'en' => 'Bulgaria'], 'code' => 'BG'],
            ['name' => ['ar' => 'بوركينا فاسو', 'en' => 'Burkina Faso'], 'code' => 'BF'],
            ['name' => ['ar' => 'بوروندي', 'en' => 'Burundi'], 'code' => 'BI'],
            ['name' => ['ar' => 'كمبوديا', 'en' => 'Cambodia'], 'code' => 'KH'],
            ['name' => ['ar' => 'الكاميرون', 'en' => 'Cameroon'], 'code' => 'CM'],
            ['name' => ['ar' => 'كندا', 'en' => 'Canada'], 'code' => 'CA'],
            ['name' => ['ar' => 'الرأس الأخضر', 'en' => 'Cape Verde'], 'code' => 'CV'],
            ['name' => ['ar' => 'جمهورية أفريقيا الوسطى', 'en' => 'Central African Republic'], 'code' => 'CF'],
            ['name' => ['ar' => 'تشاد', 'en' => 'Chad'], 'code' => 'TD'],
            ['name' => ['ar' => 'تشيلي', 'en' => 'Chile'], 'code' => 'CL'],
            ['name' => ['ar' => 'الصين', 'en' => 'China'], 'code' => 'CN'],
            ['name' => ['ar' => 'كولومبيا', 'en' => 'Colombia'], 'code' => 'CO'],
            ['name' => ['ar' => 'جزر القمر', 'en' => 'Comoros'], 'code' => 'KM'],
            ['name' => ['ar' => 'الكونغو', 'en' => 'Congo'], 'code' => 'CG'],
            ['name' => ['ar' => 'كوستاريكا', 'en' => 'Costa Rica'], 'code' => 'CR'],
            ['name' => ['ar' => 'كرواتيا', 'en' => 'Croatia'], 'code' => 'HR'],
            ['name' => ['ar' => 'كوبا', 'en' => 'Cuba'], 'code' => 'CU'],
            ['name' => ['ar' => 'قبرص', 'en' => 'Cyprus'], 'code' => 'CY'],
            ['name' => ['ar' => 'التشيك', 'en' => 'Czech Republic'], 'code' => 'CZ'],
            ['name' => ['ar' => 'الدانمرك', 'en' => 'Denmark'], 'code' => 'DK'],
            ['name' => ['ar' => 'جيبوتي', 'en' => 'Djibouti'], 'code' => 'DJ'],
            ['name' => ['ar' => 'دومينيكا', 'en' => 'Dominica'], 'code' => 'DM'],
            ['name' => ['ar' => 'جمهورية الدومينيكان', 'en' => 'Dominican Republic'], 'code' => 'DO'],
            ['name' => ['ar' => 'الإكوادور', 'en' => 'Ecuador'], 'code' => 'EC'],
            ['name' => ['ar' => 'مصر', 'en' => 'Egypt'], 'code' => 'EG'],
            ['name' => ['ar' => 'السلفادور', 'en' => 'El Salvador'], 'code' => 'SV'],
            ['name' => ['ar' => 'غينيا الاستوائية', 'en' => 'Equatorial Guinea'], 'code' => 'GQ'],
            ['name' => ['ar' => 'إريتريا', 'en' => 'Eritrea'], 'code' => 'ER'],
            ['name' => ['ar' => 'إستونيا', 'en' => 'Estonia'], 'code' => 'EE'],
            ['name' => ['ar' => 'إسواتيني', 'en' => 'Eswatini'], 'code' => 'SZ'],
            ['name' => ['ar' => 'إثيوبيا', 'en' => 'Ethiopia'], 'code' => 'ET'],
            ['name' => ['ar' => 'فيجي', 'en' => 'Fiji'], 'code' => 'FJ'],
            ['name' => ['ar' => 'فنلندا', 'en' => 'Finland'], 'code' => 'FI'],
            ['name' => ['ar' => 'فرنسا', 'en' => 'France'], 'code' => 'FR'],
            ['name' => ['ar' => 'الغابون', 'en' => 'Gabon'], 'code' => 'GA'],
            ['name' => ['ar' => 'غامبيا', 'en' => 'Gambia'], 'code' => 'GM'],
            ['name' => ['ar' => 'جورجيا', 'en' => 'Georgia'], 'code' => 'GE'],
            ['name' => ['ar' => 'ألمانيا', 'en' => 'Germany'], 'code' => 'DE'],
            ['name' => ['ar' => 'غانا', 'en' => 'Ghana'], 'code' => 'GH'],
            ['name' => ['ar' => 'اليونان', 'en' => 'Greece'], 'code' => 'GR'],
            ['name' => ['ar' => 'غرينادا', 'en' => 'Grenada'], 'code' => 'GD'],
            ['name' => ['ar' => 'غواتيمالا', 'en' => 'Guatemala'], 'code' => 'GT'],
            ['name' => ['ar' => 'غينيا', 'en' => 'Guinea'], 'code' => 'GN'],
            ['name' => ['ar' => 'غينيا بيساو', 'en' => 'Guinea-Bissau'], 'code' => 'GW'],
            ['name' => ['ar' => 'غويانا', 'en' => 'Guyana'], 'code' => 'GY'],
            ['name' => ['ar' => 'هايتي', 'en' => 'Haiti'], 'code' => 'HT'],
            ['name' => ['ar' => 'هندوراس', 'en' => 'Honduras'], 'code' => 'HN'],
            ['name' => ['ar' => 'المجر', 'en' => 'Hungary'], 'code' => 'HU'],
            ['name' => ['ar' => 'آيسلندا', 'en' => 'Iceland'], 'code' => 'IS'],
            ['name' => ['ar' => 'الهند', 'en' => 'India'], 'code' => 'IN'],
            ['name' => ['ar' => 'إندونيسيا', 'en' => 'Indonesia'], 'code' => 'ID'],
            ['name' => ['ar' => 'إيران', 'en' => 'Iran'], 'code' => 'IR'],
            ['name' => ['ar' => 'العراق', 'en' => 'Iraq'], 'code' => 'IQ'],
            ['name' => ['ar' => 'إيرلندا', 'en' => 'Ireland'], 'code' => 'IE'],
            ['name' => ['ar' => 'إسرائيل', 'en' => 'Israel'], 'code' => 'IL'],
            ['name' => ['ar' => 'إيطاليا', 'en' => 'Italy'], 'code' => 'IT'],
            ['name' => ['ar' => 'جامايكا', 'en' => 'Jamaica'], 'code' => 'JM'],
            ['name' => ['ar' => 'اليابان', 'en' => 'Japan'], 'code' => 'JP'],
            ['name' => ['ar' => 'الأردن', 'en' => 'Jordan'], 'code' => 'JO'],
            ['name' => ['ar' => 'كازاخستان', 'en' => 'Kazakhstan'], 'code' => 'KZ'],
            ['name' => ['ar' => 'كينيا', 'en' => 'Kenya'], 'code' => 'KE'],
            ['name' => ['ar' => 'كيريباتي', 'en' => 'Kiribati'], 'code' => 'KI'],
            ['name' => ['ar' => 'كوريا الشمالية', 'en' => 'North Korea'], 'code' => 'KP'],
            ['name' => ['ar' => 'كوريا الجنوبية', 'en' => 'South Korea'], 'code' => 'KR'],
            ['name' => ['ar' => 'الكويت', 'en' => 'Kuwait'], 'code' => 'KW'],
            ['name' => ['ar' => 'قيرغيزستان', 'en' => 'Kyrgyzstan'], 'code' => 'KG'],
            ['name' => ['ar' => 'لاوس', 'en' => 'Laos'], 'code' => 'LA'],
            ['name' => ['ar' => 'لاتفيا', 'en' => 'Latvia'], 'code' => 'LV'],
            ['name' => ['ar' => 'لبنان', 'en' => 'Lebanon'], 'code' => 'LB'],
            ['name' => ['ar' => 'ليسوتو', 'en' => 'Lesotho'], 'code' => 'LS'],
            ['name' => ['ar' => 'ليبيريا', 'en' => 'Liberia'], 'code' => 'LR'],
            ['name' => ['ar' => 'ليبيا', 'en' => 'Libya'], 'code' => 'LY'],
            ['name' => ['ar' => 'ليختنشتاين', 'en' => 'Liechtenstein'], 'code' => 'LI'],
            ['name' => ['ar' => 'ليتوانيا', 'en' => 'Lithuania'], 'code' => 'LT'],
            ['name' => ['ar' => 'لوكسمبورغ', 'en' => 'Luxembourg'], 'code' => 'LU'],
            ['name' => ['ar' => 'مدغشقر', 'en' => 'Madagascar'], 'code' => 'MG'],
            ['name' => ['ar' => 'مالاوي', 'en' => 'Malawi'], 'code' => 'MW'],
            ['name' => ['ar' => 'ماليزيا', 'en' => 'Malaysia'], 'code' => 'MY'],
            ['name' => ['ar' => 'المالديف', 'en' => 'Maldives'], 'code' => 'MV'],
            ['name' => ['ar' => 'مالي', 'en' => 'Mali'], 'code' => 'ML'],
            ['name' => ['ar' => 'مالطا', 'en' => 'Malta'], 'code' => 'MT'],
            ['name' => ['ar' => 'جزر مارشال', 'en' => 'Marshall Islands'], 'code' => 'MH'],
            ['name' => ['ar' => 'موريتانيا', 'en' => 'Mauritania'], 'code' => 'MR'],
            ['name' => ['ar' => 'موريشيوس', 'en' => 'Mauritius'], 'code' => 'MU'],
            ['name' => ['ar' => 'المكسيك', 'en' => 'Mexico'], 'code' => 'MX'],
            ['name' => ['ar' => 'ميكرونيزيا', 'en' => 'Micronesia'], 'code' => 'FM'],
            ['name' => ['ar' => 'مولدوفا', 'en' => 'Moldova'], 'code' => 'MD'],
            ['name' => ['ar' => 'موناكو', 'en' => 'Monaco'], 'code' => 'MC'],
            ['name' => ['ar' => 'منغوليا', 'en' => 'Mongolia'], 'code' => 'MN'],
            ['name' => ['ar' => 'الجبل الأسود', 'en' => 'Montenegro'], 'code' => 'ME'],
            ['name' => ['ar' => 'المغرب', 'en' => 'Morocco'], 'code' => 'MA'],
            ['name' => ['ar' => 'موزمبيق', 'en' => 'Mozambique'], 'code' => 'MZ'],
            ['name' => ['ar' => 'ميانمار', 'en' => 'Myanmar'], 'code' => 'MM'],
            ['name' => ['ar' => 'ناميبيا', 'en' => 'Namibia'], 'code' => 'NA'],
            ['name' => ['ar' => 'ناورو', 'en' => 'Nauru'], 'code' => 'NR'],
            ['name' => ['ar' => 'نيبال', 'en' => 'Nepal'], 'code' => 'NP'],
            ['name' => ['ar' => 'هولندا', 'en' => 'Netherlands'], 'code' => 'NL'],
            ['name' => ['ar' => 'نيوزيلندا', 'en' => 'New Zealand'], 'code' => 'NZ'],
            ['name' => ['ar' => 'نيكاراغوا', 'en' => 'Nicaragua'], 'code' => 'NI'],
            ['name' => ['ar' => 'النيجر', 'en' => 'Niger'], 'code' => 'NE'],
            ['name' => ['ar' => 'نيجيريا', 'en' => 'Nigeria'], 'code' => 'NG'],
            ['name' => ['ar' => 'مقدونيا الشمالية', 'en' => 'North Macedonia'], 'code' => 'MK'],
            ['name' => ['ar' => 'النرويج', 'en' => 'Norway'], 'code' => 'NO'],
            ['name' => ['ar' => 'عُمان', 'en' => 'Oman'], 'code' => 'OM'],
            ['name' => ['ar' => 'باكستان', 'en' => 'Pakistan'], 'code' => 'PK'],
            ['name' => ['ar' => 'بالاو', 'en' => 'Palau'], 'code' => 'PW'],
            ['name' => ['ar' => 'فلسطين', 'en' => 'Palestine'], 'code' => 'PS'],
            ['name' => ['ar' => 'بنما', 'en' => 'Panama'], 'code' => 'PA'],
            ['name' => ['ar' => 'بابوا غينيا الجديدة', 'en' => 'Papua New Guinea'], 'code' => 'PG'],
            ['name' => ['ar' => 'باراغواي', 'en' => 'Paraguay'], 'code' => 'PY'],
            ['name' => ['ar' => 'بيرو', 'en' => 'Peru'], 'code' => 'PE'],
            ['name' => ['ar' => 'الفلبين', 'en' => 'Philippines'], 'code' => 'PH'],
            ['name' => ['ar' => 'بولندا', 'en' => 'Poland'], 'code' => 'PL'],
            ['name' => ['ar' => 'البرتغال', 'en' => 'Portugal'], 'code' => 'PT'],
            ['name' => ['ar' => 'قطر', 'en' => 'Qatar'], 'code' => 'QA'],
            ['name' => ['ar' => 'رومانيا', 'en' => 'Romania'], 'code' => 'RO'],
            ['name' => ['ar' => 'روسيا', 'en' => 'Russia'], 'code' => 'RU'],
            ['name' => ['ar' => 'رواندا', 'en' => 'Rwanda'], 'code' => 'RW'],
            ['name' => ['ar' => 'سانت كيتس ونيفيس', 'en' => 'Saint Kitts and Nevis'], 'code' => 'KN'],
            ['name' => ['ar' => 'سانت لوسيا', 'en' => 'Saint Lucia'], 'code' => 'LC'],
            ['name' => ['ar' => 'سانت فنسنت وجزر غرينادين', 'en' => 'Saint Vincent and the Grenadines'], 'code' => 'VC'],
            ['name' => ['ar' => 'ساموا', 'en' => 'Samoa'], 'code' => 'WS'],
            ['name' => ['ar' => 'سان مارينو', 'en' => 'San Marino'], 'code' => 'SM'],
            ['name' => ['ar' => 'ساو تومي وبرينسيب', 'en' => 'Sao Tome and Principe'], 'code' => 'ST'],
            ['name' => ['ar' => 'السعودية', 'en' => 'Saudi Arabia'], 'code' => 'SA'],
            ['name' => ['ar' => 'السنغال', 'en' => 'Senegal'], 'code' => 'SN'],
            ['name' => ['ar' => 'صربيا', 'en' => 'Serbia'], 'code' => 'RS'],
            ['name' => ['ar' => 'سيشل', 'en' => 'Seychelles'], 'code' => 'SC'],
            ['name' => ['ar' => 'سيراليون', 'en' => 'Sierra Leone'], 'code' => 'SL'],
            ['name' => ['ar' => 'سنغافورة', 'en' => 'Singapore'], 'code' => 'SG'],
            ['name' => ['ar' => 'سلوفاكيا', 'en' => 'Slovakia'], 'code' => 'SK'],
            ['name' => ['ar' => 'سلوفينيا', 'en' => 'Slovenia'], 'code' => 'SI'],
            ['name' => ['ar' => 'جزر سليمان', 'en' => 'Solomon Islands'], 'code' => 'SB'],
            ['name' => ['ar' => 'الصومال', 'en' => 'Somalia'], 'code' => 'SO'],
            ['name' => ['ar' => 'جنوب أفريقيا', 'en' => 'South Africa'], 'code' => 'ZA'],
            ['name' => ['ar' => 'جنوب السودان', 'en' => 'South Sudan'], 'code' => 'SS'],
            ['name' => ['ar' => 'إسبانيا', 'en' => 'Spain'], 'code' => 'ES'],
            ['name' => ['ar' => 'سريلانكا', 'en' => 'Sri Lanka'], 'code' => 'LK'],
            ['name' => ['ar' => 'السودان', 'en' => 'Sudan'], 'code' => 'SD'],
            ['name' => ['ar' => 'سورينام', 'en' => 'Suriname'], 'code' => 'SR'],
            ['name' => ['ar' => 'السويد', 'en' => 'Sweden'], 'code' => 'SE'],
            ['name' => ['ar' => 'سويسرا', 'en' => 'Switzerland'], 'code' => 'CH'],
            ['name' => ['ar' => 'سوريا', 'en' => 'Syria'], 'code' => 'SY'],
            ['name' => ['ar' => 'تايوان', 'en' => 'Taiwan'], 'code' => 'TW'],
            ['name' => ['ar' => 'طاجيكستان', 'en' => 'Tajikistan'], 'code' => 'TJ'],
            ['name' => ['ar' => 'تنزانيا', 'en' => 'Tanzania'], 'code' => 'TZ'],
            ['name' => ['ar' => 'تايلاند', 'en' => 'Thailand'], 'code' => 'TH'],
            ['name' => ['ar' => 'تيمور الشرقية', 'en' => 'Timor-Leste'], 'code' => 'TL'],
            ['name' => ['ar' => 'توغو', 'en' => 'Togo'], 'code' => 'TG'],
            ['name' => ['ar' => 'تونغا', 'en' => 'Tonga'], 'code' => 'TO'],
            ['name' => ['ar' => 'ترينيداد وتوباغو', 'en' => 'Trinidad and Tobago'], 'code' => 'TT'],
            ['name' => ['ar' => 'تونس', 'en' => 'Tunisia'], 'code' => 'TN'],
            ['name' => ['ar' => 'تركيا', 'en' => 'Turkey'], 'code' => 'TR'],
            ['name' => ['ar' => 'تركمانستان', 'en' => 'Turkmenistan'], 'code' => 'TM'],
            ['name' => ['ar' => 'توفالو', 'en' => 'Tuvalu'], 'code' => 'TV'],
            ['name' => ['ar' => 'أوغندا', 'en' => 'Uganda'], 'code' => 'UG'],
            ['name' => ['ar' => 'أوكرانيا', 'en' => 'Ukraine'], 'code' => 'UA'],
            ['name' => ['ar' => 'الإمارات', 'en' => 'United Arab Emirates'], 'code' => 'AE'],
            ['name' => ['ar' => 'المملكة المتحدة', 'en' => 'United Kingdom'], 'code' => 'GB'],
            ['name' => ['ar' => 'الولايات المتحدة الأمريكية', 'en' => 'United States'], 'code' => 'US'],
            ['name' => ['ar' => 'أوروغواي', 'en' => 'Uruguay'], 'code' => 'UY'],
            ['name' => ['ar' => 'أوزبكستان', 'en' => 'Uzbekistan'], 'code' => 'UZ'],
            ['name' => ['ar' => 'فانواتو', 'en' => 'Vanuatu'], 'code' => 'VU'],
            ['name' => ['ar' => 'فنزويلا', 'en' => 'Venezuela'], 'code' => 'VE'],
            ['name' => ['ar' => 'فيتنام', 'en' => 'Vietnam'], 'code' => 'VN'],
            ['name' => ['ar' => 'اليمن', 'en' => 'Yemen'], 'code' => 'YE'],
            ['name' => ['ar' => 'زامبيا', 'en' => 'Zambia'], 'code' => 'ZM'],
            ['name' => ['ar' => 'زيمبابوي', 'en' => 'Zimbabwe'], 'code' => 'ZW'],
        ];

        foreach ($countries as $country) {
            DB::table('countries')->insert([
                'name' => json_encode(['en' => $country['name']['en'], 'ar' => $country['name']['ar']]),
                'code' => $country['code'],
            ]);
        }

        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
