<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\DigitalLibraryLinkResource\Pages;
use App\Models\DigitalLibraryLink;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class DigitalLibraryLinkResource extends Resource
{
    use Translatable;

    protected static ?string $model = DigitalLibraryLink::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function getNavigationGroup(): ?string
    {
        return __('general.navigation.digital-library'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('general.digital_library_links'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('general.digital_library_links'); // TODO: Change the autogenerated stub
    }

    public static function getModelLabel(): string
    {
        return __('general.digital_library_links'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('title')
                    ->label(__('general.title'))
                    ->required(),
                Forms\Components\TextInput::make('description')
                    ->label(__('general.description'))
                    ->required(),
                Forms\Components\TextInput::make('link')
                    ->label(__('general.link'))
                    ->required()
                    ->maxLength(255),
                Forms\Components\FileUpload::make('cover')
                    ->label(__('general.cover'))
                    ->required(),
                Forms\Components\Toggle::make('status')
                    ->label(__('general.status'))
                    ->required(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('title')
                    ->label(__('general.title'))
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('link')
                    ->label(__('general.link'))
                    ->searchable(),
                Tables\Columns\ToggleColumn::make('status')
                    ->label(__('general.status'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('general.created_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('general.updated_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDigitalLibraryLinks::route('/'),
            'create' => Pages\CreateDigitalLibraryLink::route('/create'),
            'edit' => Pages\EditDigitalLibraryLink::route('/{record}/edit'),
        ];
    }
}
