<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\DigitalLibraryTagResource\Pages;
use App\Models\DigitalLibraryTag;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class DigitalLibraryTagResource extends Resource
{
    protected static ?string $model = DigitalLibraryTag::class;

    protected static ?string $navigationIcon = 'hugeicons-tags';

    protected static ?int $navigationSort = 2;

    public static function getNavigationGroup(): ?string
    {
        return __('general.navigation.digital-library'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('general.digital_library_tags'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('general.digital_library_tags'); // TODO: Change the autogenerated stub
    }

    public static function getModelLabel(): string
    {
        return __('general.digital_library_tags'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->label(__('general.name'))
                    ->required()
                    ->live(onBlur: true)
                    ->afterStateUpdated(fn (Forms\Set $set, ?string $state) => $set('slug', $state))
                    ->maxLength(255),
                Forms\Components\TextInput::make('slug')
                    ->label(__('general.slug'))
                    ->required()
                    ->disabled()
                    ->maxLength(255),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('general.name'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('slug')
                    ->label(__('general.slug'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('general.created_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('general.updated_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDigitalLibraryTags::route('/'),
            'create' => Pages\CreateDigitalLibraryTag::route('/create'),
            'edit' => Pages\EditDigitalLibraryTag::route('/{record}/edit'),
        ];
    }
}
