<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\FeedbackResource\Pages;
use App\Models\Feedback;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class FeedbackResource extends Resource
{
    protected static ?string $model = Feedback::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function getNavigationGroup(): ?string
    {
        return __('general.settings'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('general.feedback-survey-title'); // الملاحظات
    }

    public static function getPluralModelLabel(): string
    {
        return __('general.feedback-survey-title'); // الملاحظات
    }

    public static function getModelLabel(): string
    {
        return __('general.feedback-survey-title'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('user_type')
                    ->label(__('general.user_type')) // نوع المستخدم
                    ->numeric(),

                Forms\Components\TextInput::make('general_impression')
                    ->label(__('general.general_impression')) // الانطباع العام
                    ->numeric(),

                Forms\Components\TextInput::make('ease')
                    ->label(__('general.ease')) // سهولة الاستخدام
                    ->numeric(),

                Forms\Components\TextInput::make('speed')
                    ->label(__('general.speed')) // سرعة الاستخدام
                    ->numeric(),

                Forms\Components\TextInput::make('meet_your_needs')
                    ->label(__('general.meet_your_needs')) // تلبية الاحتياجات
                    ->numeric(),

                Forms\Components\TextInput::make('clarity')
                    ->label(__('general.clarity')) // وضوح المعلومات
                    ->numeric(),

                Forms\Components\Textarea::make('comment')
                    ->label(__('general.comment')) // التعليق
                    ->columnSpanFull(),

                Forms\Components\Textarea::make('phone_number')
                    ->label(__('general.phone_number')) // رقم الهاتف
                    ->columnSpanFull(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('user_type')
                    ->label(__('general.user_type'))
                    ->badge()
                    ->sortable(),

                Tables\Columns\TextColumn::make('general_impression')
                    ->label(__('general.general_impression'))
                    ->badge()
                    ->sortable(),

                Tables\Columns\TextColumn::make('ease')
                    ->label(__('general.ease'))
                    ->badge()
                    ->sortable(),

                Tables\Columns\TextColumn::make('speed')
                    ->label(__('general.speed'))
                    ->badge()
                    ->sortable(),

                Tables\Columns\TextColumn::make('meet_your_needs')
                    ->label(__('general.meet_your_needs'))
                    ->badge()
                    ->sortable(),

                Tables\Columns\TextColumn::make('clarity')
                    ->label(__('general.clarity'))
                    ->badge()
                    ->sortable(),

                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('general.created_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),

                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('general.updated_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([])
            ->actions([
                Tables\Actions\EditAction::make()->label(__('general.edit')),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make()->label(__('general.delete')),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListFeedback::route('/'),
            'create' => Pages\CreateFeedback::route('/create'),
            'edit' => Pages\EditFeedback::route('/{record}/edit'),
        ];
    }
}
