<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\FieldOfStudyResource\Pages;
use App\Models\FieldOfStudy;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class FieldOfStudyResource extends Resource
{
    use Translatable;

    protected static ?string $model = FieldOfStudy::class;

    protected static ?string $navigationIcon = 'hugeicons-study-lamp';

    public static function getNavigationGroup(): ?string
    {
        return __('general.settings'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('general.field_of_studies'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('general.field_of_studies'); // TODO: Change the autogenerated stub
    }

    public static function getModelLabel(): string
    {
        return __('general.field_of_studies'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Textarea::make('name')
                    ->required()
                    ->label(__('general.name'))
                    ->columnSpanFull(),
                Forms\Components\Select::make('parent_id')
                    ->label(__('general.parent_category'))
                    ->relationship('parent', 'name'),
                Forms\Components\Textarea::make('description')
                    ->label(__('general.description'))
                    ->columnSpanFull(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('general.name'))
                    ->searchable()

                    ->sortable(),
                Tables\Columns\TextColumn::make('parent.name')
                    ->label(__('general.parent_category'))
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('deleted_at')
                    ->label(__('general.deleted_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('general.created_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('general.updated_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListFieldOfStudies::route('/'),
            'create' => Pages\CreateFieldOfStudy::route('/create'),
            'edit' => Pages\EditFieldOfStudy::route('/{record}/edit'),
        ];
    }
}
