<?php

namespace App\Filament\Admin\Resources;

use App\Enums\Status;
use App\Filament\Admin\Resources\JobApplicationResource\Pages;
use App\Models\JobApplication;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class JobApplicationResource extends Resource
{
    protected static ?string $model = JobApplication::class;

    protected static ?string $navigationIcon = 'hugeicons-permanent-job';

    public static function getNavigationGroup(): ?string
    {
        return __('general.entity'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('general.job_applications'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('general.job_applications'); // TODO: Change the autogenerated stub
    }

    public static function getModelLabel(): string
    {
        return __('general.job_applications'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('title')
                    ->label(__('general.title'))
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('position')
                    ->label(__('general.position'))
                    ->required()
                    ->maxLength(255),
                Forms\Components\RichEditor::make('description')
                    ->label(__('general.description'))
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('apply_link')
                    ->label(__('general.apply_link'))
                    ->required()
                    ->url()
                    ->maxLength(255),
                Forms\Components\Select::make('job_department_id')
                    ->label(__('general.department'))
                    ->required()
                    ->relationship('jobDepartment', 'name'),
                Forms\Components\Select::make('province_id')
                    ->label(__('general.province'))
                    ->required()
                    ->relationship('province', 'name'),
                Forms\Components\TextInput::make('salary')
                    ->label(__('general.salary'))
                    ->prefix('OMR')
                    ->required()
                    ->maxLength(255),
                Forms\Components\Select::make('employment_type_id')
                    ->label(__('general.employment_type'))
                    ->required()
                    ->relationship('employmentType', 'name'),
                Forms\Components\Select::make('education_type_id')
                    ->label(__('general.education_type'))
                    ->required()
                    ->relationship('educationType', 'name'),
                Forms\Components\Select::make('experience_level_id')
                    ->label(__('general.experience_level'))
                    ->required()
                    ->relationship('experienceLevel', 'name'),
                Forms\Components\Select::make('categories')
                    ->label(__('general.categories'))
                    ->preload()
                    ->relationship('categories', 'name')
                    ->multiple(),
                Forms\Components\Select::make('skills')
                    ->label(__('general.skills'))
                    ->preload()
                    ->relationship('skills', 'name')
                    ->multiple(),
                Forms\Components\Select::make('tools')
                    ->label(__('general.tools'))
                    ->preload()
                    ->relationship('tools', 'name')
                    ->multiple(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('entity.name')
                    ->label(__('general.entity'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('title')
                    ->label(__('general.title'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('position')
                    ->label(__('general.position'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('province.name')
                    ->label(__('general.province'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('salary')
                    ->label(__('general.salary'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('employmentType.name')
                    ->label(__('general.employment_type'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('educationType.name')
                    ->label(__('general.education_type'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('experienceLevel.name')
                    ->label(__('general.experience_level'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('status')
                    ->label(__('general.status'))
                    ->badge()
                    ->sortable(),
                Tables\Columns\TextColumn::make('deleted_at')
                    ->label(__('general.deleted_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('general.created_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('general.updated_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\Action::make('activate')
                    ->label(__('general.activate'))
                    ->action(fn (JobApplication $record) => $record->update(['status' => Status::Active]))
                    ->after(fn () => Notification::make()->title(__('general.activated'))->success()->send())
                    ->color('success')
                    ->icon('heroicon-o-check-circle'),

                Tables\Actions\Action::make('deactivate')
                    ->label(__('general.deactivate'))
                    ->action(fn (JobApplication $record) => $record->update(['status' => Status::Inactive]))
                    ->after(fn () => Notification::make()->title(__('general.deactivated'))->success()->send())
                    ->color('danger')
                    ->icon('heroicon-o-x-circle'),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListJobApplications::route('/'),
            'create' => Pages\CreateJobApplication::route('/create'),
            'edit' => Pages\EditJobApplication::route('/{record}/edit'),
        ];
    }
}
