<?php

namespace App\Filament\Admin\Resources;

use App\Actions\ActivateAction;
use App\Actions\DeactivateAction;
use App\Filament\Admin\Resources\MediaCenterPostResource\Pages;
use App\Models\MediaCenterPost;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Forms\Set;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Support\Str;

class MediaCenterPostResource extends Resource
{
    use Translatable;

    protected static ?string $model = MediaCenterPost::class;

    protected static ?string $navigationIcon = 'hugeicons-file-01';

    public static function getNavigationGroup(): ?string
    {
        return __('general.navigation.media-center'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('general.media_center_posts'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('general.media_center_posts'); // TODO: Change the autogenerated stub
    }

    public static function getModelLabel(): string
    {
        return __('general.media_center_posts'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('user_id')
                    ->relationship('user', 'name')
                    ->label(__('general.user'))
                    ->required(),
                Forms\Components\TextInput::make('title')
                    ->label(__('general.title'))
                    ->live(onBlur: true)
                    ->required()
                    ->afterStateUpdated(fn (Set $set, ?string $state) => $set('slug', Str::slug($state)))
                    ->maxLength(255),
                Forms\Components\TextInput::make('slug')
                    ->label(__('general.slug'))
                    ->required()
                    ->maxLength(255)
                    ->unique(MediaCenterPost::class, 'slug', ignoreRecord: true)
                    ->disabled(),
                Forms\Components\Textarea::make('content')
                    ->label(__('general.content'))
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\FileUpload::make('image')
                    ->label(__('general.image'))
                    ->image(),
                Forms\Components\Toggle::make('status')
                    ->label(__('general.status')),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('user.name')
                    ->numeric()
                    ->label(__('general.user'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('title')
                    ->label(__('general.title'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('slug')
                    ->label(__('general.slug'))
                    ->searchable(),
                Tables\Columns\ImageColumn::make('image')->label(__('general.image'))
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('status')
                    ->label(__('general.status'))
                    ->badge()
                    ->sortable(),
                Tables\Columns\TextColumn::make('deleted_at')
                    ->label(__('general.deleted_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('general.created_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('general.updated_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                ActivateAction::make(),
                DeactivateAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListMediaCenterPosts::route('/'),
            'create' => Pages\CreateMediaCenterPost::route('/create'),
            'edit' => Pages\EditMediaCenterPost::route('/{record}/edit'),
        ];
    }
}
