<?php

namespace App\Filament\Admin\Resources;

use App\Actions\ActivateAction;
use App\Actions\DeactivateAction;
use App\Filament\Admin\Resources\MediaCenterCommentResource\Pages;
use App\Models\MediaCenterComment;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class MediaCenterCommentResource extends Resource
{
    protected static ?string $model = MediaCenterComment::class;

    protected static ?string $navigationIcon = 'hugeicons-comment-02';

    protected static ?int $navigationSort = 3;

    public static function getNavigationGroup(): ?string
    {
        return __('general.navigation.media-center'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('general.media_center_comments'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('general.media_center_comments'); // TODO: Change the autogenerated stub
    }

    public static function getModelLabel(): string
    {
        return __('general.media_center_comments'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('media_center_post_id')
                    ->label(__('general.post'))
                    ->required()
                    ->numeric(),
                Forms\Components\TextInput::make('user_id')
                    ->label(__('general.user'))
                    ->required()
                    ->numeric(),
                Forms\Components\Textarea::make('content')
                    ->label(__('general.comment'))
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('status')
                    ->label(__('general.status'))
                    ->required()
                    ->numeric()
                    ->default(0),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('post.title')
                    ->label(__('general.post'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('user.name')
                    ->label(__('general.user'))
                    ->sortable(),
                Tables\Columns\TextColumn::make('status')
                    ->label(__('general.status'))
                    ->badge()
                    ->sortable(),
                Tables\Columns\TextColumn::make('deleted_at')
                    ->label(__('general.deleted_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('general.created_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('general.updated_at'))
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                ActivateAction::make(),
                DeactivateAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListMediaCenterComments::route('/'),
            'create' => Pages\CreateMediaCenterComment::route('/create'),
            'edit' => Pages\EditMediaCenterComment::route('/{record}/edit'),
        ];
    }
}
