<?php

namespace App\Filament\Admin\Resources;

use App\Filament\Admin\Resources\RecruitmentPlatformResource\Pages;
use App\Models\RecruitmentPlatform;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Concerns\Translatable;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class RecruitmentPlatformResource extends Resource
{
    use Translatable;

    protected static ?string $model = RecruitmentPlatform::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function getNavigationGroup(): ?string
    {
        return __('general.entity'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('general.recruitment_platforms'); // منصات التوظيف
    }

    public static function getPluralModelLabel(): string
    {
        return __('general.recruitment_platforms'); // منصات التوظيف
    }

    public static function getModelLabel(): string
    {
        return __('general.recruitment_platform'); // منصة توظيف
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('description')
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('url')
                    ->columnSpanFull(),
                Forms\Components\FileUpload::make('logo')->image(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('logo')
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListRecruitmentPlatforms::route('/'),
            'create' => Pages\CreateRecruitmentPlatform::route('/create'),
            'edit' => Pages\EditRecruitmentPlatform::route('/{record}/edit'),
        ];
    }
}
