<?php

namespace App\Filament\Admin\Resources;

use App\Enums\Status;
use App\Filament\Admin\Resources\WorkResource\Pages;
use App\Models\Work;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Support\Enums\FontWeight;
use Filament\Tables;
use Filament\Tables\Table;

class WorkResource extends Resource
{
    protected static ?string $model = Work::class;

    protected static ?string $navigationIcon = 'hugeicons-work-history';

    public static function getNavigationGroup(): ?string
    {
        return __('general.works'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationLabel(): string
    {
        return __('general.works'); // TODO: Change the autogenerated stub
    }

    public static function getPluralModelLabel(): string
    {
        return __('general.works'); // TODO: Change the autogenerated stub
    }

    public static function getModelLabel(): string
    {
        return __('general.works'); // TODO: Change the autogenerated stub
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('work_category_id')
                    ->label(__('general.category'))
                    ->relationship('workCategory', 'name')
                    ->required(),
                Forms\Components\Select::make('profile_id')
                    ->label(__('general.profile'))
                    ->relationship('profile', 'id')
                    ->required(),
                Forms\Components\TextInput::make('title')
                    ->label(__('general.title'))
                    ->required()
                    ->maxLength(255),
                Forms\Components\TextInput::make('slug')
                    ->label(__('general.slug'))
                    ->required()
                    ->maxLength(255),
                Forms\Components\Textarea::make('description')
                    ->label(__('general.description'))
                    ->required()
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('images')
                    ->label(__('general.images'))
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('cover')
                    ->label(__('general.cover'))
                    ->maxLength(255),
                Forms\Components\Textarea::make('video')
                    ->label(__('general.video'))
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('attachments')
                    ->label(__('general.attachments'))
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('attachment_file_names')
                    ->label(__('general.attachment_file_names'))
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('link')
                    ->label(__('general.link'))
                    ->maxLength(255),
                Forms\Components\Textarea::make('tools')
                    ->label(__('general.tools'))
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('status')
                    ->label(__('general.status'))
                    ->required()
                    ->numeric()
                    ->default(1),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\Layout\Stack::make([
                    Tables\Columns\ImageColumn::make('cover')
                        ->height('100%')
                        ->width('100%'),
                    Tables\Columns\Layout\Stack::make([
                        Tables\Columns\TextColumn::make('title')
                            ->weight(FontWeight::Bold),
                    ]),
                ])->space(3),
            ])
            ->filters([
                //
            ])
            ->contentGrid([
                'md' => 2,
                'xl' => 3,
            ])
            ->paginated([
                18,
                36,
                72,
                'all',
            ])
            ->actions([
                Tables\Actions\Action::make('visit')
                    ->label(__('general.visit'))
                    ->icon('heroicon-m-arrow-top-right-on-square')
                    ->color('gray')
                    ->url(fn (Work $record) => route('works.show', $record))
                    ->openUrlInNewTab(),
                Tables\Actions\EditAction::make(),
            ])
            ->filters([
                Tables\Filters\SelectFilter::make('profile')
                    ->relationship('profile', 'fullname')
                    ->searchable(),
                Tables\Filters\SelectFilter::make('status')
                    ->options(Status::class),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListWorks::route('/'),
            'create' => Pages\CreateWork::route('/create'),
            'edit' => Pages\EditWork::route('/{record}/edit'),
        ];
    }
}
